  
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: https://prometheus-cs-production.up.railway.app
    basicAuth: false
    isDefault: true
    editable: true